rutismo/apps/ruta/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.staticfiles.urls import static
from.views import *
app_name = "ruta"

urlpatterns = [
    path('dasboard/', login_required(Dasboard.as_view()), name='dasboard'),
    path('comenzar/', login_required(Comenzar.as_view()), name='comenzar'),
    path('elige/', login_required(Elige.as_view()), name='elige'),
    path('estado/', login_required(Estado.as_view()), name='estado'),
    path('horarios/', login_required(Horarios.as_view()), name='horarios'),
    path('ayuda/', login_required(Ayuda.as_view()), name='ayuda'),
    path('Listanino/', login_required(ListadoNino.as_view()), name='listaNino'),
    
    
    path('registro_nino/', login_required(CrearNino.as_view()), name='crear_nino'),
]

rutismo/apps/usuarios/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from.views import Login, Logout, Inicio,CustomerUserCreateView
app_name = "usuario"
urlpatterns = [
    path('',(Inicio.as_view()), name='index'),
    path('accounts/login/', Login.as_view(), name='login'),
    path('logout/', login_required(Logout.as_view()), name='logout'),
    path('register/',CustomerUserCreateView.as_view(), name='register'),
]

rutismo/rutismo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # URLS Authentications
    path('', include('apps.usuarios.urls'), name='usuario'),

    # URLS APPS Rutismo

    path('ruta/', include('apps.ruta.urls'), name='ruta'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

rutismo/apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <!-- https://cdnjs.com/libraries/twitter-bootstrap/5.0.0-beta1 -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css"
    />

    <!-- Icons: https://getbootstrap.com/docs/5.0/extend/icons/ -->
    <!-- https://cdnjs.com/libraries/font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    />

    <title>
        {% block title %}
            ::RUTISMO::
            
        {% endblock title %}
        </title>
  </head>
  <style>
    .bg-primary{
      background-color:#c2daff !important;
    }
    .btn-primary{
      
    }

            .gradient-custom-2 {
                /* fallback for old browsers */
                background: #fccb90;

                /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, #29fcd8, #418bfa, #1cec8b, #ffd037);
        
        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, #29fcd8, #418bfa, #1cec8b, #ffd037);
        }

        @media (min-width: 768px) {
            .gradient-form {
                height: 100vh !important;
            }
        }
        @media (min-width: 769px) {
            .gradient-custom-2 {
                border-top-right-radius: .3rem;
                border-bottom-right-radius: .3rem;
            }
        }
        .abs-center {
          display: flex;
          align-items: center;
          justify-content: center;
          min-height: 100vh;
        }
</style>
  <body>
    <nav class="navbar navbar-dark bg-primary navbar-expand-md fixed-top p-3 mb-5" ">
        <div class="container">
            <a href="{% url 'ruta:dasboard' %}"
            ><img  src="{% static 'images/logo.png' %}" width="100px" height="60px"
          /></a>
          <ul class="navbar-nav ms-auto">
              
            {% if user.first_name != null %}
            
            <li class="nav-item  dropdown">
              <a class="nav-link text-dark fw-bold fst-italic dropdown-toggle align-items-center ms-auto" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                
                <img src="{{ user.avatar.url}}" alt="" width="60" height="60" class="rounded-circle">

                {{ user.first_name| upper }}
              </a>
              <ul class="dropdown-menu ms-auto" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'ruta:crear_nino'%}">Registrar Nino</a></li>
                <li><a class="dropdown-item" href="{% url 'ruta:listaNino' %}">Listado de Niños</a></li>
                <li><a class="dropdown-item" href="{% url 'usuario:logout' %}">Salir</a></li>
            </ul>
        </div>
            
            {% endif %}

    </nav>
    <div class="abs-center">
      {% block container %}
      
      {% endblock container %}
    </div>
        
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.bundle.min.js"></script>
    <footer
      class="pie-de-pagina bg-primary bg-opacity-25 text-center fixed-bottom"
      >
      <p class="m-0 py-3">Copyright @ 2021. Todos los derechos reservados
        <a href="{%  url 'ruta:ayuda' %}" >Ayuda</a>
      </p>
    </footer> 

  </body>
</html>

rutismo/apps/templates/estado.html
{% extends 'base.html' %}
    
    {% block title %}
        RUTISMO:::Estado
    {% endblock title %}
        
      {% block container %}
    <h1>Aqui se construye la seccion Estado</h1>
      {% endblock container %}

rutismo/apps/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    RUTISMO:::HOME
{% endblock title %}
    
{% block container %}
 
    <div class="pt-5 mt-5">
    
 
<div class="container">

    
    
    <div class="row">
        <h1 class="text-center fw-bold text-primary mt-3 mb-1">Bienvenido  {{ user.first_name| upper }}</h1>

        <div class="col-12 col-md-8 mx-auto mt-5 d-md-flex">
            <div class="card me-md-2" style="width: 18rem">
              <center>
                <img
                  src="{% static 'images/edit.png' %}"
                  class=""
                  alt="..."
                  height="80px"
                  width="60px"
                />
              </center>
              <div class="card-body">
                <div class="card-footer">
                  <center>
                    <a href="{% url 'ruta:comenzar' %}" class="btn btn-primary">Comenzar</a>
                  </center>
                </div>
              </div>
            </div>
            <div class="card me-md-2" style="width: 18rem">
              <center>
                <img
                  src="{% static 'images/estados.png' %}"
                  class=""
                  alt="..."
                  height="80px"
                  width="140px"
                />
              </center>
              <div class="card-body">
                <div class="card-footer">
                  <center>
                    <a href="{%  url 'ruta:estado'%}" class="btn btn-primary">Estado</a>
                  </center>
                </div>
              </div>
            </div>
            <div class="card" style="width: 18rem">
              <center>
                <img
                  src="{% static 'images/horario.png' %}"
                  class=""
                  alt="..."
                  height="80px"
                  width="100px"
                />
              </center>
              <div class="card-body">
                <div class="card-footer">
                  <center>
                    <a href="{%  url 'ruta:horarios' %}" class="btn btn-primary">Horarios</a>
                  </center>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6 mx-auto d-md-flex mt-2">
            <div class="card me-md-2" style="width: 18rem">
              <center>
                <img
                  src="{% static 'images/nino2.png' %}"
                  class=""
                  alt="..."
                  height="80px"
                  width="60px"
                />
              </center>
              <div class="card-body" >
                <div class="card-footer">
                  <center>
                    <a href="{%  url 'ruta:elige'%}" class="btn btn-primary">¿Como Estas?</a>
                  </center>
                </div>
              </div>
            </div>



    
    </div>
</div>
</div>
<!-- footer donde se hubica el copyright -->

    {% endblock container %}
    

rutismo/apps/templates/horarios.html
{% extends 'base.html' %}

    
    {% block title %}
       RUTISMO:::Horarios
    {% endblock title %}
        
    {% block container %}
        
        <h1>
            aqui se construye la seccion Horarios
        
        </h1>

    {% endblock container %}

rutismo/apps/templates/index.html
{% extends 'base.html' %}
{% load static %}
    
    {% block container %}

    <div class="container">
        <div class="abs-center" style="text-align: center;">
            <div>
                <div class="card text-black" style="background-color: #c2daff; width: 500px; height: 550px; border-radius: 10%;">
                    <div class="text-center">
                        <img src="{% static '/images/logo.png' %}" style="width: 140px; margin-top: 10px;" alt="logo">
                        <h4 class="mt-1 mb-5 pb-1">Creando rutas para los buenos habitos</h4>
                    </div>
            
                    <div>
                        <div>
                            <div>
                                <a title="Login" href="{% url 'usuario:login' %}">
                                    <img id="login" src="{% static '/images/login.jpg' %}" style="width: 300px; height: 300px; border-radius: 15%; box-shadow: 2px 2px 5px #999;" alt="login">
                                </a>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 
            
    {% endblock container %}
        
 

rutismo/apps/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <!-- https://cdnjs.com/libraries/twitter-bootstrap/5.0.0-beta1 -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css"
    />

    <!-- Icons: https://getbootstrap.com/docs/5.0/extend/icons/ -->
    <!-- https://cdnjs.com/libraries/font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    />

     <!-- Bootstrap CSS -->
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
      crossorigin="anonymous"> 

    <title>RUTISMO::LOGIN</title>
<style>

            .gradient-custom-2 {
                /* fallback for old browsers */
                background: #fccb90;

                /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, #29fcd8, #418bfa, #1cec8b, #ffd037);
        
        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, #29fcd8, #418bfa, #1cec8b, #ffd037);
        }

        @media (min-width: 768px) {
            .gradient-form {
                height: 100vh !important;
            }
        }
        @media (min-width: 769px) {
            .gradient-custom-2 {
                border-top-right-radius: .3rem;
                border-bottom-right-radius: .3rem;
            }
        }
</style>
  </head>
  <body class="d-flex vw-100 vh-100 align-items-center justify-content-center">
        <section class="h-100 gradient-form" >
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10" style="margin-top: -25px;">
                <div class="card rounded-3 text-black" style="background-color: #c2daff; box-shadow: 2px 2px 5px #999;"> 
                  <div class="row g-0">
                    <div class="col-lg-6">
                    <div class="card-body p-md-5 mx-md-4">

                        <div class="text-center">
                        <img src="{% static '/images/logo.png' %}" style="width: 140px;" alt="logo">
                        <h4 class="mt-1 mb-5 pb-1">Creando rutas para los buenos habitos</h4>
                        </div>
                      
                        <form method="POST">
                              {% csrf_token %}
                            {% if not form.error_messages %}
                              <div class="alert alert-danger alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss = "alert" aria-label = "Close">
                                  <span aria-hidden = "true">&times;</span>
                                </button>
                                <strong>Advertencia: </strong> {{ form.get_invalid_login_error }}
                              </div>
                          {% endif %}
                        <p>Bienvenido. Por favor, ingrese a su cuenta</p>

                        <div class="form-outline mb-4">
                            <label class="form-label" for="form2Example11">Usuario</label>
                             {{ form.username }}
                        </div>

                        <div class="form-outline mb-4">
                            <label class="form-label" for="form2Example22">Contraseña</label>
                            {{ form.password }}
                        </div>

                        <div class="text-center pt-1 mb-5 pb-1">
                            <button class="btn btn-primary btn-block fa-lg gradient-custom-2" type="submit">Entrar</button>
                            <button class="btn btn-primary btn-danger fa-lg mb-0" type="button" role="link" onclick="window.location='{% url 'usuario:index'%}'"> Cancelar </button>
                            <br>
                            
                        </div>

                        <div class="d-flex align-items-center justify-content-center pb-4">
                            <p class="mb-0 me-2">¿No tienes una cuenta?</p>
                            <button type="button" class="btn btn-outline-danger" role="link" onclick="window.location='{% url 'usuario:register' %}'">Registrate</button>
                        </div>

                        </form>

                    </div>
                    </div>
                    <div class="col-lg-6 d-flex align-items-center">
                      <div id="carouselExampleCaptions" class="carousel carousel-dark slide" data-bs-ride="carousel">
                        <div class="carousel-indicators">
                          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        </div>
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img src="{% static '/images/Daniel.jpeg' %}" style="height: 715px; width: 460px; border-radius: 1%;" class="d-block w-100" alt="1">
                            <div class="carousel-caption d-none d-md-block">
                              <strong><h5 style="color:white">Daniel 11 Años</h5></strong>
                             
                            </div>
                          </div>
                          <div class="carousel-item">
                            <img src="{% static '/images/Alejandro.jpeg' %}" style="height: 715px; width: 460px; border-radius: 1%;" class="d-block w-100" alt="2">
                            <div class="carousel-caption d-none d-md-block">
                              <strong><h5 style="color:white">Alejandro 13 Años</h5></strong>
                             
                            </div>
                          </div>
                          <div class="carousel-item">
                            <img src="{% static '/images/ramon.jpeg' %}" style="height: 715px; width: 460px; border-radius: 1%;" class="d-block w-100" alt="3">
                            <div class="carousel-caption d-none d-md-block">
                              <strong><h5 style="color:white">Ramon 12 Años</h5></strong>
                              
                            </div>
                          </div>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
            </div>
        </div>
        </section>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
      crossorigin="anonymous">
    </script>       
  </body>
</html>

rutismo/apps/templates/register_user.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Rustimos::Registro
{% endblock title %}
    

      {% block container %}
      <nav class="navbar navbar-dark bg-primary navbar-expand-md fixed-top p-3 mb-5" ">
        <div class="container">
            <a href="../index.html"
             ><img  src="{% static 'images/logo.png' %}" width="100px" height="60px"
           /></a>
          
    </div>
    
    </nav> 
      <div class="container my-5 pt-5">
        <div class="row">
          <div class="col-6 mt-3">

          
            <h3 class="fw-bold fst-italic text-center">Registro</h3>
  

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {% if form.errors %}
          
          {{ form.errors }}</h2>
       <h2>
      {% endif %}     
      
      {% for field in form  %}
      <div class="mb-3"></div>
      <label for="" class="form-label">{{field.label}}</label>
      
      <input type="{{ field.field.widget.input_type }}"
       class="form-control" 
       name="{{ field.name }}" 
       placeholder="{{ field.label }}" />
      
 
      {% endfor %}
      <br>
      <div class="text-center pt-1 mb-5 pb-1">
        <button class="btn btn-primary" type="submit">Registrar</button>
        <button class="btn btn-primary btn-danger" type="button" role="link" onclick="window.location='{% url 'usuario:login'%}'"> Cancelar </button>
                            
      </div>
    </form>
    </div>
    <div class="col-6 align-self-center">
      <img
        class="img-thumbnail"
        src="{% static 'images/ninos.jpg' %}""
        alt="risas"
        height="100%"
        width="100%"
      />
    </div>
  </div>
    
  </div>
  <footer
  class="pie-de-pagina bg-primary bg-opacity-25 text-center fixed-bottom"
  >
  <p class="m-0 py-3">Copyright @ 2021. Todos los derechos reservados</p>
  </footer>
      {% endblock container %}